### ISSUE TITLE
Javascript testing

### ISSUE THREAD

**Issue by rasmushaglund** [quarkiverse/quarkus-web-bundler#110]
Hello, thank you for a wonderful extension!

Is there is a way to run javascript-based tests with this extension as a part of the build? I'm looking into a way to run component tests for React components, as a compliment to the e2e/integration tests.

If there is a way I can happily help trying it out and documenting the solution.

**Comment by ia3andy** [comment]
You need to find a testing library for javascript that we could embed in Java (so it should be Java or a binary that we embed)
You could explore embedding SWC as they provide https://swc.rs/docs/usage/jest.

Once that done it's just a matter of creating a JUnit extension to bind those test to the Java ecosystem.

It seems like an interesting topic to explore.


Also @SWC could be a solid alternate implementation to esbuild for the web-bundler. I think @edewit (author of esbuild-java) have explored many of those frameworks.

**Comment by ia3andy** [comment]
I have been thinking about testing components with the web-bundler, I am not sure if we should provide a solution for it.

The reason is that I see two solutions (which seem more relevant) to this problem:
- switch to [quinoa](https://github.com/quarkiverse/quarkus-quinoa/) which is better for larger apps (it will allow to use the whole nodejs ecosystem for testing), you may still use esbuild through nodejs (or vite which uses esbuild)
- extracts the components which needs to be tested in a npm published react library, then you can use it from the web bundler

**Comment by edewit** [comment]
@ia3andy yes, that sounds more feasible and there is still the option to do playwright e2e tests

**Comment by ia3andy** [comment]
@rasmushaglund nothing prevent you from exploring what I suggested above.

**Comment by rasmushaglund** [comment]
Thank you all! It's fun, I have one project that started up using quinoa but I found the web-bundler a better fit, and now I have another project where the relation is reversed :). I'll explore these topics, and maybe component tests can be replaced with decent e2e tests.

Thank you for taking the time and answering me, your work and time is much valued.

**Comment by ia3andy** [comment]
Thanks for the kind words, it's much appreciated.

I'll close this issue for now, feel free to re-open.

@rasmushaglund  FYI I just added the doc for locking web deps if you haven't yet seen it, it might be interesting for react apps with the web-bundler:
https://docs.quarkiverse.io/quarkus-web-bundler/dev/advanced-guides.html#locking

**Comment by ia3andy** [comment]
@all-contributors please add @rasmushaglund for idea
