### ISSUE TITLE
Dev mode broken when using `clean`

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-web-bundler#190]
If you use `mvn clean quarkus:dev` and use the dev mode, the bundle is deleted and so... cannot be loaded anymore.

```
GET http://localhost:8080/static/bundle/main-I37LK3HR.js net::ERR_ABORTED 404 (Not Found)
```

**Comment by ia3andy** [comment]
@cescoffier are you using 1.4.0?

**Comment by ia3andy** [comment]
I suppose you are experiencing this: https://github.com/quarkiverse/quarkus-web-bundler/issues/171

**Comment by cescoffier** [comment]
I am using the latest.

**Comment by cescoffier** [comment]
Sorry, the variable was not use it uses 1.3.1 - fixing it.

**Comment by cescoffier** [comment]
Will re-open if it's happening again.

**Comment by ia3andy** [comment]
Just for context:
- When changing a file
- The bundler is updating the file and creating a new js with a hash
- The index.html is updated

=> but because of the cache issue, it was keeping the previous index.html, so using the old js hash.

With the fix, I am instantiating the Vert.x StaticHandler from the Web Bundler and cache is disabled in devmode.



At some point I think we should make this available in Quarkus core:
- Use a specific static handler for external resources (webjars, mvnpm, ...)
- Use a non cached static handler for local resources (meta-inf/resources)

This would allow to use the BuildItems from extensions instead of instantiating the static handler.
