### ISSUE TITLE
Connection problem with browser-live-reload=true on Firefox

### ISSUE THREAD

**Issue by mkouba** [quarkiverse/quarkus-web-bundler#260]
It seems that when a form is submitted on a page with `live-reload.js` included then an HTTP connection may be closed while the HTTP request is being processed. As a result, the `UniResponseHandler` from `quarkus-rest` attempts to cancel the subscription of the returned `Uni`. In my reproducer, we have `quarkus-hibernate-reactive-panache` where a cancellation results in a transaction rollback (and sometimes even in inconsistent state - this is something I'd like to investigate further with someone from HR) and a broken HTTP response.

Works fine on Chromium (Version 127.0.6533.72).

I've tried to debug the code and it seems that on Firefox  (v128.0.3) the `EventSource` receives an onerror event after the form is submitted here:
https://github.com/quarkiverse/quarkus-web-bundler/blob/main/deployment/src/main/resources/web-bundler/live-reload.js#L51

Then the `EventSource#close()` is invoked and the connection is closed.

If I set a breakpoint to [live-reload.js#L51](https://github.com/quarkiverse/quarkus-web-bundler/blob/main/deployment/src/main/resources/web-bundler/live-reload.js#L51) and keep it paused (i.e. avoid calling `EventSource#close()`) then the HTTP request is processed normally.

### Reproducer

Here's the reproducer: https://github.com/mkouba/quarkus-quickstarts/tree/web-bundler-browser-live-reload

Steps to reproduce:
1. `mvn quarkus:dev`
2. open `http://localhost:8080/creatures` with Firefox
3. hit the "create" button

### Current result

Sometimes the transaction is silently rolled back and you'll see nothing. Sometimes you'll see some data. The "delete" button usually does not work for the same reason - connection is closed, transaction rolled back, etc.

### Expected result

You should see a table with 20000 records. The "delete" button should work without problems.

### Solution

`quarkus.web-bundler.browser-live-reload=false` or do no use Firefox.

**Comment by DavideD** [comment]
I've tried to debug this issue and what I've noticed is that, when `cancellable.cancel()` in [UniResponseHandler](https://github.com/quarkusio/quarkus/blob/35f4c4afd041045074aab004ab1d6a5f7cfb80e9/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/UniResponseHandler.java#L40) caused [MutinySessionImpl.Transaction#rollback](https://github.com/hibernate/hibernate-reactive/blob/c61ec35fbe63aeb3b49aeb293f6077c363ce3253/hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java#L509) to be called as expected.

Two things in particular aren't clear to me:
1. What's causing  the cancel of subscription in `UniResponseHandler`?
2. The rollback returns a uni, but `cancellable.cancel()` is not reactive. Should we close the request before the rollback has finished?

I suspect reactive doesn't log anything because the rollback is called directly and there are no exception and the return value is ignored. But I'm still debugging.

**Comment by ia3andy** [comment]
It seems that closing the event source during a transaction happening on another request is cancelling the unrelated transaction.

**Comment by ia3andy** [comment]
Ok, I've managed to create a new live-reload.js that uses the browser SSE re-connection manager and no need to cancel the connection manually anymore. I will publish a fix soon.

Still I think there is something undercover this issue.

**Comment by mkouba** [comment]
I can confirm that https://github.com/quarkiverse/quarkus-web-bundler/pull/268 fixed the problem but I agree with Andy that there's probably another issue underneath. Unfortunately, I have no idea how to reproduce it now. 

> The rollback returns a uni, but cancellable.cancel() is not reactive. Should we close the request before the rollback has finished?

@DavideD good point. @cescoffier @geoand WDYT?

**Comment by ia3andy** [comment]
Web-Bundler is doing this:
```java
 private void closeConnection(Connection connection) {
        connections.remove(connection);
        if (!connection.closed.getAndSet(true)) {
            connection.ctx().vertx().cancelTimer(connection.timerId());
            if (!connection.ctx().response().ended()) {
                connection.ctx().response().end();
            }
        }
    }
    ```
    
    
    I've debug it's only closing the SSE connection, not any other connection..
